CREATE TABLE transactions (
    row_id                INTEGER,
    trans_date_trans_time TIMESTAMP,
    cc_num                BIGINT,
    merchant              TEXT,
    category              TEXT,
    amt                   NUMERIC(10,2),
    first_name            TEXT,
    last_name             TEXT,
    gender                CHAR(1),
    street                TEXT,
    city                  TEXT,
    state                 CHAR(2),
    zip                   TEXT,
    lat                   NUMERIC(9,6),
    lon                   NUMERIC(9,6),
    city_pop              INTEGER,
    job                   TEXT,
    dob                   DATE,
    trans_num             TEXT,
    unix_time             BIGINT,
    merch_lat             NUMERIC(9,6),
    merch_long            NUMERIC(9,6),
    is_fraud              SMALLINT
);